#!/bin/bash
echo "Nothing to see here"
echo "post"
set -euo pipefail
#
jupyter serverextension enable --py nbserverproxy --sys-prefix
# labextensions
echo "hell yeah"
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet
#@jupyter-widgets/jupyterlab-manager \
#
# download data
cd /home/jovyan
bash ./binder/provision.sh
cd /home/jovyan